# Generated by Django 5.0.3 on 2024-04-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBH', '0002_alter_profile_id_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
