# Generated by Django 5.0.3 on 2024-04-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBH', '0005_alter_profile_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=13),
        ),
    ]
