# Generated by Django 5.0.3 on 2024-04-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBH', '0022_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_living_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gmail_id',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='native_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
